__title__ = "flake8-junit-report-basic"
__summary__ = "Simple tool that converts a flake8 file to junit format"
__version__ = "3.0.0"
__license__ = "BSD 3-Clause License"
__uri__ = "https://github.com/ricardogarfe/flake8-junit-report"
__author__ = "Ricardo García Fernández"
__email__ = "ricardogarfe@gmail.com"
